name: saludo
env:
  GLOBAL_DATA: "dato global"
on: 
  push:
    branches:
      - main


jobs:
  saludar-job:
    runs-on: ubuntu-latest


    steps:
      - name: mostrar saludo
        run: echo "hola desde github actions" 

      - name: mostrar perfil
        env:
          USUARIO_ACTUAL: ${{ github.actor }}
        run: |
          echo " 1 autor: $USUARIO_ACTUAL "
          echo " 2 evento: ${{ github.event_name }} "
          echo " 3 repo: ${{ github.repository }} "
          echo " 4 ref: ${{ github.ref_name }} "
          echo " 5 global: $GLOBAL_DATA "

      - name: condiciones1
        if: github.event_name == 'push' && github.ref == 'ref/heads/main'
        run: echo "evento push activado hacia main" 

      - name: condiciones2
        if: github.event_name == 'pull_request'
        run: echo "evento pull request activado"
          
      
