name: saludo

on: 
  push:
    branches:
      - main


jobs:
  saludar-job:
    runs-on: ubuntu-latest


    steps:
      - name: mostrar saludo
        run: echo "hola desde github actions" 

      - name: mostrar perfil
        run: |
          echo " autor: ${{ github.actor }} "
          echo "evento: ${{ github.event_name }} "
          echo "repo: ${{ github.repository }} "
          echo "ref: ${{ github.ref_name }} "
          
      
